import { withTRPC } from "@trpc/next";
import type { AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import { Toaster } from "react-hot-toast";
import superjson from "superjson";
import type { AppRouter } from "../server/router";
import "../styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Arsa&apos;s Personal Drive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextNProgress />
      <Component {...pageProps} />
      <Toaster />
    </>
  );
};

export default withTRPC<AppRouter>({
  config({ ctx }) {
    if (typeof window !== "undefined") {
      // during client requests
      return {
        transformer: superjson, // optional - adds superjson serialization
        url: "/api/trpc",
      };
    }
    const url = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}/api/trpc`
      : "http://localhost:3000/api/trpc";

    return {
      url,
      transformer: superjson,
      headers: {
        "x-ssr": "1",
        ...ctx?.req?.headers,
      },
    };
  },
  /**
   * @link https://trpc.io/docs/ssr
   */
  ssr: true,
})(MyApp);
